; pokedex ids
; indexes for:
; - BaseStats (see data/pokemon/base_stats.asm)
; - MonPartyData (see data/pokemon/menu_icons.asm)
; - MonsterPalettes (see data/pokemon/palettes.asm)
	const_def 1
	const DEX_SNIVY      ; 1
	const DEX_SERVINE    ; 2
	const DEX_SERPERIOR  ; 3
	const DEX_TEPIG      ; 4
	const DEX_PIGNITE    ; 5
	const DEX_EMBOAR     ; 6
	const DEX_OSHAWOTT   ; 7
	const DEX_DEWOTT     ; 8
	const DEX_SAMUROTT   ; 9
	const DEX_PATRAT     ; 10
	const DEX_WATCHOG    ; 11
	const DEX_LILLIPUP   ; 12
	const DEX_HERDIER    ; 13
	const DEX_STOUTLAND  ; 14
	const DEX_PURRLOIN   ; 15
	const DEX_LIEPARD    ; 16
	const DEX_PANSAGE    ; 17
	const DEX_SIMISAGE   ; 18
	const DEX_PANSEAR    ; 19
	const DEX_SIMISEAR   ; 20
	const DEX_PANPOUR    ; 21
	const DEX_SIMIPOUR   ; 22
	const DEX_MUNNA      ; 23
	const DEX_MUSHARNA   ; 24
	const DEX_PIDOVE     ; 25
	const DEX_TRANQUILL  ; 26
	const DEX_UNFEZANT   ; 27
	const DEX_BLITZLE    ; 28
	const DEX_ZEBSTRIKA  ; 29
	const DEX_ROGGENROLA ; 30
	const DEX_BOLDORE    ; 31
	const DEX_GIGALITH   ; 32
	const DEX_WOOBAT     ; 33
	const DEX_SWOOBAT    ; 34
	const DEX_DRILBUR    ; 35
	const DEX_EXCADRILL  ; 36
	const DEX_AUDINO     ; 37
	const DEX_TIMBURR    ; 38
	const DEX_GURDURR    ; 39
	const DEX_CONKELDURR ; 40
	const DEX_TYMPOLE    ; 41
	const DEX_PALPITOAD  ; 42
	const DEX_SEISMITOAD ; 43
	const DEX_THROH      ; 44
	const DEX_SAWK       ; 45
	const DEX_SEWADDLE   ; 46
	const DEX_SWADLOON   ; 47
	const DEX_LEAVANNY   ; 48
	const DEX_WEEDLE     ; 13
	const DEX_KAKUNA     ; 14
	const DEX_BEEDRILL   ; 15
	const DEX_SPEAROW    ; 21
	const DEX_FEAROW     ; 22
	const DEX_VENUSAUR   ; 32
	const DEX_NIDORINO   ; 33
	const DEX_NIDOKING   ; 34
	const DEX_VULPIX     ; 37
	const DEX_NINETALES  ; 38
	const DEX_JIGGLYPUFF ; 39
	const DEX_WIGGLYTUFF ; 40
	const DEX_VILEPLUME  ; 45
	const DEX_PARAS      ; 46
	const DEX_PARASECT   ; 47
	const DEX_VENONAT    ; 48
	const DEX_VENOMOTH   ; 49
	const DEX_DIGLETT    ; 50
	const DEX_DUGTRIO    ; 51
	const DEX_MEOWTH     ; 52
	const DEX_PERSIAN    ; 53
	const DEX_PSYDUCK    ; 54
	const DEX_GOLDUCK    ; 55
	const DEX_MANKEY     ; 56
	const DEX_PRIMEAPE   ; 57
	const DEX_GROWLITHE  ; 58
	const DEX_ARCANINE   ; 59
	const DEX_ABRA       ; 63
	const DEX_KADABRA    ; 64
	const DEX_ALAKAZAM   ; 65
	const DEX_BELLSPROUT ; 69
	const DEX_WEEPINBELL ; 70
	const DEX_VICTREEBEL ; 71
	const DEX_TENTACOOL  ; 72
	const DEX_TENTACRUEL ; 73
	const DEX_PONYTA     ; 77
	const DEX_RAPIDASH   ; 78
	const DEX_SLOWPOKE   ; 79
	const DEX_SLOWBRO    ; 80
	const DEX_MAGNEMITE  ; 81
	const DEX_MAGNETON   ; 82
	const DEX_DODUO      ; 84
	const DEX_DODRIO     ; 85
	const DEX_GRIMER     ; 88
	const DEX_MUK        ; 89
	const DEX_SHELLDER   ; 90
	const DEX_CLOYSTER   ; 91
	const DEX_GASTLY     ; 92
	const DEX_HAUNTER    ; 93
	const DEX_GENGAR     ; 94
	const DEX_ONIX       ; 95
	const DEX_DROWZEE    ; 96
	const DEX_HYPNO      ; 97
	const DEX_KRABBY     ; 98
	const DEX_KINGLER    ; 99
	const DEX_VOLTORB    ; 100
	const DEX_ELECTRODE  ; 101
	const DEX_EXEGGCUTE  ; 102
	const DEX_EXEGGUTOR  ; 103
	const DEX_CUBONE     ; 104
	const DEX_MAROWAK    ; 105
	const DEX_KOFFING    ; 109
	const DEX_WEEZING    ; 110
	const DEX_RHYHORN    ; 111
	const DEX_PIKACHU  ; 112
	const DEX_TANGELA    ; 114
	const DEX_RAICHU    ; 115
	const DEX_HORSEA     ; 116
	const DEX_SEADRA     ; 117
	const DEX_GOLDEEN    ; 118
	const DEX_SEAKING    ; 119
	const DEX_STARYU     ; 120
	const DEX_STARMIE    ; 121
	const DEX_MR_MIME    ; 122
	const DEX_SCYTHER    ; 123
	const DEX_JYNX       ; 124
	const DEX_ELECTABUZZ ; 125
	const DEX_MAGMAR     ; 126
	const DEX_PINSIR     ; 127
	const DEX_TAUROS     ; 128
	const DEX_MAGIKARP   ; 129
	const DEX_GYARADOS   ; 130
	const DEX_LAPRAS     ; 131
	const DEX_DITTO      ; 132
	const DEX_EEVEE      ; 133
	const DEX_VAPOREON   ; 134
	const DEX_JOLTEON    ; 135
	const DEX_FLAREON    ; 136
	const DEX_PORYGON    ; 137
	const DEX_OMANYTE    ; 138
	const DEX_OMASTAR    ; 139
	const DEX_KABUTO     ; 140
	const DEX_KABUTOPS   ; 141
	const DEX_AERODACTYL ; 142
	const DEX_SNORLAX    ; 143
	const DEX_ARTICUNO   ; 144
	const DEX_ZAPDOS     ; 145
	const DEX_MOLTRES    ; 146
	const DEX_DRATINI    ; 147
	const DEX_DRAGONAIR  ; 148
	const DEX_DRAGONITE  ; 149
	const DEX_MEWTWO     ; 150
	const DEX_MEW        ; 151

DEF NUM_POKEMON EQU const_value - 1
