; pokedex ids
; indexes for:
; - BaseStats (see data/pokemon/base_stats.asm)
; - MonPartyData (see data/pokemon/menu_icons.asm)
; - MonsterPalettes (see data/pokemon/palettes.asm)
	const_def 1
	const DEX_SNIVY      ; 1
	const DEX_SERVINE    ; 2
	const DEX_SERPERIOR  ; 3
	const DEX_TEPIG      ; 4
	const DEX_PIGNITE    ; 5
	const DEX_EMBOAR     ; 6
	const DEX_OSHAWOTT   ; 7
	const DEX_DEWOTT     ; 8
	const DEX_SAMUROTT   ; 9
	const DEX_PATRAT     ; 10
	const DEX_WATCHOG    ; 11
	const DEX_LILLIPUP   ; 12
	const DEX_HERDIER    ; 13
	const DEX_STOUTLAND  ; 14
	const DEX_PURRLOIN   ; 15
	const DEX_LIEPARD    ; 16
	const DEX_PANSAGE    ; 17
	const DEX_SIMISAGE   ; 18
	const DEX_PANSEAR    ; 19
	const DEX_SIMISEAR   ; 20
	const DEX_PANPOUR    ; 21
	const DEX_SIMIPOUR   ; 22
	const DEX_MUNNA      ; 23
	const DEX_MUSHARNA   ; 24
	const DEX_PIDOVE     ; 25
	const DEX_TRANQUILL  ; 26
	const DEX_UNFEZANT   ; 27
	const DEX_BLITZLE    ; 28
	const DEX_ZEBSTRIKA  ; 29
	const DEX_ROGGENROLA ; 30
	const DEX_BOLDORE    ; 31
	const DEX_GIGALITH   ; 32
	const DEX_WOOBAT     ; 33
	const DEX_SWOOBAT    ; 34
	const DEX_DRILBUR    ; 35
	const DEX_EXCADRILL  ; 36
	const DEX_AUDINO     ; 37
	const DEX_TIMBURR    ; 38
	const DEX_GURDURR    ; 39
	const DEX_CONKELDURR ; 40
	const DEX_TYMPOLE    ; 41
	const DEX_PALPITOAD  ; 42
	const DEX_SEISMITOAD ; 43
	const DEX_THROH      ; 44
	const DEX_SAWK       ; 45
	const DEX_SEWADDLE   ; 46
	const DEX_SWADLOON   ; 47
	const DEX_LEAVANNY   ; 48
	const DEX_VENIPEDE   ; 49
	const DEX_WHIRLIPEDE ; 50
	const DEX_SCOLIPEDE  ; 51
	const DEX_COTTONEE   ; 52
	const DEX_WHIMSICOTT ; 53
	const DEX_PETILIL    ; 54
	const DEX_LILLIGANT  ; 55
	const DEX_BASCULIN   ; 56
	const DEX_SANDILE    ; 57
	const DEX_KROKOROK   ; 58
	const DEX_KROOKODILE ; 59
	const DEX_DARUMAKA   ; 58
	const DEX_DARMANITAN ; 59
	const DEX_MARACTUS   ; 60
	const DEX_DWEBBLE    ; 61
	const DEX_CRUSTLE    ; 62
	const DEX_SCRAGGY    ; 63
	const DEX_SCRAFTY    ; 64
	const DEX_SIGILYPH   ; 65
	const DEX_YAMASK     ; 65
	const DEX_COFAGRIGUS ; 66
	const DEX_TIRTOUGA   ; 67
	const DEX_CARRACOSTA ; 68
	const DEX_ARCHEN     ; 69
	const DEX_ARCHEOPS   ; 70
	const DEX_TRUBBISH   ; 71
	const DEX_GARBODOR   ; 72
	const DEX_ZORUA      ; 73
	const DEX_ZOROARK    ; 74
	const DEX_MINCCINO   ; 75
	const DEX_CINCCINO   ; 76
	const DEX_GOTHITA    ; 77
	const DEX_GOTHORITA  ; 78
	const DEX_GOTHITELLE ; 79
	const DEX_SOLOSIS    ; 80
	const DEX_DUOSION    ; 81
	const DEX_REUNICLUS  ; 82
	const DEX_DUCKLETT   ; 83
	const DEX_SWANNA     ; 84
	const DEX_VANILLITE  ; 85
	const DEX_VANILLISH  ; 86
	const DEX_VANILLUXE  ; 87
	const DEX_DEERLING   ; 88
	const DEX_SAWSBUCK   ; 89
	const DEX_EMOLGA     ; 90
	const DEX_KARRABLAST ; 91
	const DEX_ESCAVALIER ; 92
	const DEX_FOONGUS    ; 93
	const DEX_AMOONGUSS  ; 94
	const DEX_FRILLISH   ; 95
	const DEX_JELLICENT  ; 96
	const DEX_ALOMOMOLA  ; 97
	const DEX_JOLTIK     ; 98
	const DEX_GALVANTULA ; 99
	const DEX_FERROSEED  ; 100
	const DEX_FERROTHORN ; 101
	const DEX_KLINK      ; 102
	const DEX_KLANG      ; 103
	const DEX_KLINKLANG  ; 104
	const DEX_TYNAMO     ; 105
	const DEX_EELEKTRIK  ; 106
	const DEX_EELEKTROSS ; 107
	const DEX_ELGYEM     ; 108
	const DEX_BEHEEYEM   ; 109
	const DEX_SPEAROW    ; 21
	const DEX_FEAROW     ; 22
	const DEX_NIDORINO   ; 33
	const DEX_NIDOKING   ; 34
	const DEX_VILEPLUME  ; 45
	const DEX_PONYTA     ; 77
	const DEX_RAPIDASH   ; 78
	const DEX_SLOWPOKE   ; 79
	const DEX_DODUO      ; 84
	const DEX_DODRIO     ; 85
	const DEX_GASTLY     ; 92
	const DEX_HAUNTER    ; 93
	const DEX_GENGAR     ; 94
	const DEX_EXEGGCUTE  ; 102
	const DEX_CUBONE     ; 104
	const DEX_MAROWAK    ; 105
	const DEX_RHYHORN    ; 111
	const DEX_PIKACHU  ; 112
	const DEX_RAICHU    ; 115
	const DEX_GOLDEEN    ; 118
	const DEX_SEAKING    ; 119
	const DEX_MR_MIME    ; 122
	const DEX_SCYTHER    ; 123
	const DEX_MAGMAR     ; 126
	const DEX_PINSIR     ; 127
	const DEX_TAUROS     ; 128
	const DEX_MAGIKARP   ; 129
	const DEX_GYARADOS   ; 130
	const DEX_DITTO      ; 132
	const DEX_PORYGON    ; 137
	const DEX_AERODACTYL ; 142
	const DEX_ARTICUNO   ; 144
	const DEX_ZAPDOS     ; 145
	const DEX_MOLTRES    ; 146
	const DEX_DRATINI    ; 147
	const DEX_DRAGONAIR  ; 148
	const DEX_DRAGONITE  ; 149
	const DEX_MEWTWO     ; 150
	const DEX_MEW        ; 151

DEF NUM_POKEMON EQU const_value - 1
